name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml up -d
          # Здесь вы можете добавить команды для запуска тестов
          # Например, если у вас есть тесты в backend:
          docker-compose -f docker-compose.yml exec backend python -m unittest discover -s tests
          docker-compose -f docker-compose.yml down

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker images
      #   run: |
      #     docker-compose -f docker-compose.yml push

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Deploy to server
  #       run: |
  #         # Здесь вы можете добавить команды для развертывания на вашем сервере
  #         # Например, если вы используете SSH для доступа к серверу:
  #         ssh -o StrictHostKeyChecking=no user@your-server-ip "cd /path/to/your/app && git pull && docker-compose -f docker-compose.yml up -d"
