name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: Run tests
        run: |
          docker compose -f docker-compose.yml up -d
          docker compose -f docker-compose.yml exec front-end npm test
          docker compose -f docker-compose.yml down

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to local host
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Установите SSH-ключ
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

        #   ssh -i private_key -o StrictHostKeyChecking=no minhhieuk19@192.168.0.1 "cd /Web2024 && docker compose -f docker-compose.yml up -d"
